POST http://localhost:3000/exercise/create_exercise_choice HTTP/1.1
Content-Type: application/json

{
    "exercise": {
        "description": "กรุณาเลือกคำตอบที่ถูกต้อง",
        "level": 1,
        "expectTime": 60,
        "skillId": 1
    },
    "exerciseChoices": [
        {
            "choiceNo": 1,
            "script": "ตัวเลือกที่ 1",
            "isAnswer": true
        },
        {
            "choiceNo": 2,
            "script": "ตัวเลือกที่ 2",
            "isAnswer": false
        },
        {
            "choiceNo": 3,
            "script": "ตัวเลือกที่ 3",
            "isAnswer": false
        },
        {
            "choiceNo": 4,
            "script": "ตัวเลือกที่ 4",
            "isAnswer": false
        }
    ]
}
