services:
  main-server:
    # build:
    #   context: ./app
    #   dockerfile: ./dockerfile
    #   target: dev
    image: registry.in.psu.ac.th:443/6610210454/adt-backend
    container_name: adt-learning-main-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      BKT_ENGINE_URL: http://bkt-engine:80
    volumes:
      - ./app:/app
      - /app/node_modules

  bkt-engine:
    # build:
    #   context: ./btk-engine
    #   dockerfile: ./dockerfile
    image: registry.in.psu.ac.th:443/6610210454/adt-backend/bkt-service
    container_name: bkt-engine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./btk-engine/app:/code/app
    environment:
      PYTHONUNBUFFERED: "1"


networks:
  default:
    name: adt-learning-net  
