FROM node:20-alpine AS base

RUN apk add --no-cache openssl
WORKDIR /app

FROM base AS deps

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
RUN npx prisma generate

FROM base AS dev

COPY --from=deps /app/node_modules ./node_modules
COPY . .

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
