services:
  app:
    image: registry.in.psu.ac.th:443/6610210454/adt-backend

    container_name: adt-learning-app
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
